"use client";

import { useState } from "react";
import type {
  TransactionMatchedResponse,
  TransactionExceptionResponse,
  TransactionNotFoundResponse,
} from "@/lib/types";
import { formatINR, formatDate } from "@/lib/formatters";
import { Copy, Check } from "lucide-react";

interface CopyAsTextProps {
  data: TransactionMatchedResponse | TransactionExceptionResponse;
}

function buildTextReport(
  data: TransactionMatchedResponse | TransactionExceptionResponse
): string {
  const lines: string[] = [];
  lines.push(`TRUEUP INVESTIGATION REPORT`);
  lines.push(`${"=".repeat(40)}`);
  lines.push(`Transaction: ${data.txn_id}`);
  lines.push(`Status: ${data.status}`);
  lines.push("");

  if (data.status === "MATCHED") {
    const m = data as TransactionMatchedResponse;
    lines.push(`MATCH DETAILS`);
    lines.push(`  Resolved by: ${m.match_pass}`);
    lines.push(`  Method: ${m.method}`);
    lines.push(`  Confidence: ${(m.confidence * 100).toFixed(1)}%`);
    lines.push(`  Amount agrees: ${m.amount_agrees ? "Yes" : "No"}`);
    if (m.date_lag_days !== undefined && m.date_lag_days !== null) {
      lines.push(`  Date lag: ${m.date_lag_days} days`);
    }
    lines.push("");
    lines.push(`SOURCE RECORDS`);
    lines.push(`  Gateway:  ${formatINR(m.gateway_amount)} on ${m.gateway_date} (fee: ${formatINR(m.gateway_fee)})`);
    if (m.bank_settlement) {
      lines.push(`  Bank:     ${formatINR(m.bank_settlement.settlement_amount)} on ${m.bank_settlement.settlement_date} (UTR: ${m.bank_settlement.utr})`);
    }
    if (m.merchant_ledger) {
      lines.push(`  Ledger:   ${formatINR(m.merchant_ledger.expected_amount)} on ${m.merchant_ledger.entry_date}`);
    }
  } else if (data.status === "EXCEPTION") {
    const e = data as TransactionExceptionResponse;
    lines.push(`EXCEPTION DETAILS`);
    lines.push(`  Type: ${e.exception_type}`);
    lines.push(`  Source: ${e.source}`);
    lines.push(`  Reason: ${e.reason}`);
    if (e.amount) lines.push(`  Amount: ${formatINR(e.amount)}`);
    if (e.date) lines.push(`  Date: ${e.date}`);
    lines.push(`  Exception ID: ${e.exception_id}`);
    if (e.linked_record_ids.length > 0) {
      lines.push(`  Linked records: ${e.linked_record_ids.join(", ")}`);
    }
    lines.push("");
    if (Object.keys(e.evidence).length > 0) {
      lines.push(`EVIDENCE`);
      for (const [key, value] of Object.entries(e.evidence)) {
        lines.push(`  ${key}: ${typeof value === "object" ? JSON.stringify(value) : String(value)}`);
      }
    }
    lines.push("");
    lines.push(`AI INVOLVEMENT: Not called`);
  } else {
    lines.push(`NOT FOUND`);
    if ("error" in data) {
      lines.push(`  ${data.error}`);
    }
  }

  lines.push("");
  lines.push(`${"=".repeat(40)}`);
  lines.push(`Generated by TrueUp — AI Finance Controller`);
  return lines.join("\n");
}

export function CopyAsText({ data }: CopyAsTextProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const text = buildTextReport(data);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <button
      onClick={handleCopy}
      className="inline-flex items-center gap-2 rounded-md border border-border bg-card px-3 py-1.5 text-xs text-muted hover:text-foreground hover:bg-card-hover transition-colors"
    >
      {copied ? (
        <>
          <Check className="h-3.5 w-3.5 text-green" />
          Copied
        </>
      ) : (
        <>
          <Copy className="h-3.5 w-3.5" />
          Copy as text
        </>
      )}
    </button>
  );
}
